import { Cabin, Exo_2 } from 'next/font/google';

import type { Metadata } from 'next';

import './globals.tw.css';
import AppProviders from 'providers/AppProviders';

const titleFont = Cabin({ subsets: ['latin'], variable: '--title-font' });
const textFont = Exo_2({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <AppProviders>
      <html
        lang="en"
        className={` ${titleFont.variable}`}
      >
        <body className={textFont.className}>{children}</body>
      </html>
    </AppProviders>
  );
}
