import { notFound } from 'next/navigation';

import { Cabin, Exo_2 } from 'next/font/google';

import type { Metadata } from 'next';

import './globals.tw.css';
import { locales } from 'languages';
import AppProviders from 'providers/AppProviders';

const titleFont = Cabin({ subsets: ['latin'], variable: '--title-font' });
const textFont = Exo_2({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default async function RootLayout({ children, params: { locale } }: Props) {
  const isValidLocale = locales.some(cur => cur === locale);
  if (!isValidLocale) notFound();

  return (
    <html
      lang={locale}
      className={` ${titleFont.variable}`}
    >
      <body className={textFont.className}>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
